name: WorkflowDev

on:
  push:
    branches-ignore:
      - master
      - main

defaults:
  run:
    working-directory: ../../main

jobs:
  dev_unittest:
    if: contains(github.event.head_commit.message, '[CI SKIP]') == false && contains(github.event.head_commit.message, '[CI AUTO]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Create folder
        working-directory: ../../
        run: mkdir main
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install necessities
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Clone 3 repos
        run: |
          mkdir repos
          cd repos
          git clone https://github.com/${{ github.repository_owner }}/generalimport.git -b ${{ github.ref_name }} || git clone https://github.com/${{ github.repository_owner }}/generalimport.git || git clone https://github.com/ManderaGeneral/generalimport.git -b ${{ github.ref_name }} || git clone https://github.com/ManderaGeneral/generalimport.git
          git clone https://github.com/${{ github.repository_owner }}/generaltool.git -b ${{ github.ref_name }} || git clone https://github.com/${{ github.repository_owner }}/generaltool.git || git clone https://github.com/ManderaGeneral/generaltool.git -b ${{ github.ref_name }} || git clone https://github.com/ManderaGeneral/generaltool.git
          git clone https://github.com/${{ github.repository_owner }}/generallibrary.git -b ${{ github.ref_name }} || git clone https://github.com/${{ github.repository_owner }}/generallibrary.git || git clone https://github.com/ManderaGeneral/generallibrary.git -b ${{ github.ref_name }} || git clone https://github.com/ManderaGeneral/generallibrary.git
      - name: Install 3 repos
        run: |
          cd repos
          pip install -e generalimport[full]
          pip install -e generaltool[full]
          pip install -e generallibrary[full]
      - name: Run unittests
        run: |
          cd repos/generallibrary/generallibrary/test
          python -m unittest discover

